### ISSUE TITLE
Compiling on macOS

### ISSUE THREAD

**Issue by tmcgilchrist** [Gopiandcode/ocamlot#3]
First thanks for writing this project, I'm excited to have something like this written in OCaml and have a chance to hack on it. The blog post on https://gopiandcode.uk/logs/log-writing-activitypub.html was great.

I'm having issues with compiling this on macOS. The `conan` dependency fails with this error in an OCaml 4.14.1 sandbox. Have you encountered this issue? Is it possible to work around not having conan available?

``` shell
$ opam install conan
The following actions will be performed:
  ∗ install conan 0.0.2

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
⬇ retrieved conan.0.0.2  (cached)
[ERROR] The compilation of conan.0.0.2 failed at "dune install --create-install-files conan".

#=== ERROR while compiling conan.0.0.2 ========================================#
# context     2.1.4 | macos/x86_64 | ocaml-base-compiler.4.14.1 | https://opam.ocaml.org/#26770281
# path        ~/code/ocaml/ocamlot/_opam/.opam-switch/build/conan.0.0.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune install --create-install-files conan
# exit-code   1
# env-file    ~/.opam/log/conan-14922-5c5eb5.env
# output-file ~/.opam/log/conan-14922-5c5eb5.out
### output ###
# Error: Unknown package conan!



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build conan 0.0.2
└─ 
╶─ No changes have been performed

```

**Comment by Gopiandcode** [comment]
Thanks for the kind words!

w.r.t your error: huh, that's a strange error message.

Have you tried updating your opam repositories? It could be that they're out of date. 

Otherwise, the other case is that this is a problem on the `conan` side itself, maybe the conan developers might be able to help (@dinosaure?).

I use `conan` for mime handling --- in theory it could be replaced by just shelling out to `find`, although then again, that might open up another can of worms with compatibility.

**Comment by tmcgilchrist** [comment]
It is strange, compiling `conan` directly from a git checkout works so it must be some packaging issue.

**Comment by tmcgilchrist** [comment]
Found https://github.com/mirage/conan/issues/19 which looks to be the same issue.

**Comment by tmcgilchrist** [comment]
Fixed in https://github.com/mirage/conan/pull/24
